#github actions
name: "workflow1"
run-name: Single job with multiple steps
on: [push]
jobs:
  alltogether:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "extract dependencies and check availability"
        run: npm ci

      - name: "Test job"
        run: npm test

      - name: "build job"
        run: npm run build