#github actions
name: "workflow1"
run-name: Single job with multiple steps
on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'
#     branches-ignore:
#       - dev
#    tags:
#      - v.1.0.0

  pull_request:
    types: [opened, reopened]
#    paths-ignore:
#      - .github/workflows/*

jobs:
  alltogether:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "extract dependencies and check availability"
        run: npm ci

      - name: "Test job"
        run: npm test

      - name: "build job"
        run: npm run build