name: "main workflow to call reusable workflow"
on :
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: |
          echo "first job"
          echo pwd
          ech ls -la
      
#      - name: wsecond-job
#        uses: .github/workflows/reusable.yml
