name: "main workflow to call reusable workflow"
on :
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: first job
        run: |
          echo "first job"
          pwd
          ls -la ./.github/workflows/*
      
      - name: second-job
        uses: ./.github/workflows/reusable.yml
