name: "main workflow to call reusable workflow"
on :
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: first job
        run: |
          echo "first job"
          pwd
          ls -la ./.github/workflows/*
  
  job2:
    uses: ./.github/workflows/reusable.yml
    with:
      username: Dike
    secrets:
      envPAT: ${{ secrets.SECRETS_SAMPLE}}
    
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: print output
        run: |
          echo ${{ needs.job2.outputs.workflow_output1}}  
