#github actions
name: "outputvariable"
run-name: outputvariable
on: 
  workflow_dispatch:
  push:
#    branches-ignore:
#      - 'main'
    branches:
      - 'dev'
#    tags:
#      - v.1.0.0

#  pull_request:
#    types: [opened, reopened]
#    paths-ignore:
#      - .github/workflows/*
jobs:
  firstjob:
    outputs:
      namevar: ${{ steps.var.outputs.name }}
      randomnyum: ${{ steps.random.outputs.ranomnumber }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
        exclude:
          - os: ubuntu-20.04
            version: 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: new variable
        id: var
        run: echo "name=Siddhesh" >> "$GITHUB_OUTPUT"

      - name: generate random number
        id: random
        run: echo "ranomnumber=$RANDOM" >> "$GITHUB_OUTPUT"
        
