name: "reusableworkflow"
on: 
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Siddhesh'
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: outputs
        run: echo "Hi from ${{ inputs.username }}"

      - name: outputs
        run: echo "Secret is ${{ inputs.envPAT }}"

