#github actions
name: "workflow1"
run-name: multiple jobs
on: [push]
jobs:
  lintjob:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

  installdep:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: "extract dependencies and check availability"
        run: npm ci
  
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "extract dependencies and check availability"
        run: npm ci

      - name: "Test job"
        run: npm test

  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: "lint job"
        uses: actions/checkout@v4
        with:
          repository: 'DevOpsuserdike/githubaction1'

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "extract dependencies and check availability"
        run: npm ci

      - name: "build job"
        run: npm run build